name: CI/CD Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            PROJECT_DIR=~/projects/footlove_backend
            REPO_URL=https://github.com/mir2x/footlove_backend.git
            BRANCH=master

            echo "Starting deployment..."

            if [ ! -d "$PROJECT_DIR" ]; then
              echo "Directory $PROJECT_DIR does not exist. Creating..."
              mkdir -p "$PROJECT_DIR"
            else
              echo "Directory $PROJECT_DIR exists."
            fi

            cd "$PROJECT_DIR"

            if [ ! -d ".git" ]; then
              echo "Directory is not a Git repository. Cloning repository..."
              git clone --branch $BRANCH $REPO_URL .
            fi

            echo "Ensuring the working directory is up-to-date..."
            git pull origin $BRANCH

            if [ "$(docker ps -q -f name=footlove-backend)" ]; then
              echo "Container 'footlove-backend' is running. Stopping and removing..."
              docker stop footlove-backend
              docker rm footlove-backend
            elif [ "$(docker ps -aq -f status=exited -f name=footlove-backend)" ]; then
              echo "Container 'footlove-backend' exists but is not running. Removing..."
              docker rm footlove-backend
            else
              echo "No existing container 'footlove-backend' found."
            fi

            echo "Building Docker image..."
            docker buildx build --platform linux/amd64 -t footlove-backend:latest --load .

            echo "Running Docker container..."
            docker run -d \
              -p 7001:7001 \
              --env-file .env \
              --restart on-failure \
              --name footlove-backend \
              footlove-backend:latest

            echo "Deployment completed successfully."
